<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <include filename="$(find andalite_description)/urdf/common.xacro"/>

    <xacro:property name="gripper_base_length" value="0.084" />
    <xacro:property name="gripper_base_width" value="0.05" />
    <xacro:property name="gripper_base_height" value="0.14" />

    <xacro:property name="finger_span" value="0.0845" />

    <xacro:property name="finger_length" value="0.07" />
    <xacro:property name="finger_width" value="${gripper_base_width}" />
    <!-- <xacro:property name="finger_height" value="${0.5 * (gripper_base_height - finger_span)}" /> -->
    <xacro:property name="finger_height" value="0.02775" />

    <!-- macro to instantiate the fake gripper -->
    <xacro:macro name="fake_gripper" params="mounting_link mounting_origin">
        <joint name="joint_gripper_base" type="fixed">
            <parent link="${mounting_link}"/>
            <child link="gripper_base"/>
            <axis xyz="0 0 1"/>
            <origin xyz="${mounting_origin}" rpy="0 0 0"/>
        </joint>

        <link name="gripper_base">
            <visual>
                <geometry>
                    <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.690"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>

        <joint name="finger1" type="prismatic">
            <parent link="gripper_base"/>
            <child link="finger_link1"/>
            <limit lower="0.001" upper="0.042" effort="45" velocity="0.38"/>
            <axis xyz="0 0 1"/>
            <origin xyz="${0.5 * (gripper_base_length + finger_length)} 0 ${-0.5 * (gripper_base_height - finger_height)}"
                    rpy="0 0 0"/>
            <dynamics damping="10" friction="0.1"/>
        </joint>

        <link name="finger_link1">
            <visual>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.1"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>

        <joint name="finger2" type="prismatic">
            <parent link="gripper_base"/>
            <child link="finger_link2"/>
            <limit lower="0.001" upper="0.042" effort="45" velocity="0.38"/>
            <axis xyz="0 0 1"/>
            <origin xyz="${0.5 * (gripper_base_length + finger_length)} 0 ${0.5 * (gripper_base_height - finger_height)}"
                    rpy="${pi} 0 0"/>
            <dynamics damping="10" friction="0.1"/>
        </joint>

        <link name="finger_link2">
            <visual>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.1"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>
    </xacro:macro>
</robot>

