<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="shelf_dist_from_bumper_m" value="0.10795"/>

    <xacro:property name="bumper_to_rail_bottom_offset_z" value="0.132"/>

    <!-- values computed from diagrams -->
    <!-- <xacro:property name="rail_width" value="0.421"/>  -->
    <!-- <xacro:property name="shelf_length_m" value="0.1524"/> -->
    <!-- <xacro:property name="shelf_width_m" value="0.0127"/> -->
    <!-- <xacro:property name="shelf_height_m" value="0.267208"/> -->
    <!-- <xacro:property name="arm_mount_panel_height_m" value="0.1778"/> -->
    <!-- <xacro:property name="arm_mount_panel_edge_offset_m" value="0.14605"/> -->

    <!-- values measured from husky at lab -->
    <xacro:property name="rail_width" value="0.418"/>
    <xacro:property name="shelf_length_m" value="0.126"/>
    <xacro:property name="shelf_width_m" value="0.00700"/>
    <xacro:property name="shelf_height_m" value="0.24324"/>
    <xacro:property name="arm_mount_panel_height_m" value="0.171"/>
    <xacro:property name="arm_mount_panel_edge_offset_m" value="0.098322"/>
    <!-- arm mount panel currently inherits thickness from the shelving unit -->

    <xacro:macro name="husky_shelf" params="mounting_link mounting_origin">
        <joint name="bottom_shelf_support_mount" type="fixed">
            <parent link="${mounting_link}"/>
            <child link="bottom_shelf_support"/>
            <origin xyz="${mounting_origin}"/>
        </joint>

        <link name="right_shelf_support">
            <visual>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${shelf_height_m}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${shelf_height_m}"/>
                </geometry>
            </collision>
        </link>

        <link name="left_shelf_support">
            <visual>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${shelf_height_m}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${shelf_height_m}"/>
                </geometry>
            </collision>
        </link>

        <link name="top_shelf">
            <visual>
                <geometry>
                    <box size="${shelf_length_m} ${rail_width + 2 * shelf_width_m} ${shelf_width_m}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${shelf_length_m} ${rail_width} ${shelf_width_m}"/>
                </geometry>
            </collision>
        </link>

        <link name="arm_mount_panel">
            <visual>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${arm_mount_panel_height_m}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${shelf_length_m} ${shelf_width_m} ${arm_mount_panel_height_m}"/>
                </geometry>
            </collision>
        </link>

        <link name="arm_mount_panel_dummy">
        </link>

        <link name="kinect_frame_dummy">
        </link>

        <joint name="right_shelf_support_mount" type="fixed">
            <parent link="base_link_front_bumper_part"/>
            <child link="right_shelf_support"/>
            <origin xyz="${-shelf_dist_from_bumper_m - 0.5 * shelf_length_m}
                         ${-0.5 * rail_width - 0.5 * shelf_width_m}
                         ${bumper_to_rail_bottom_offset_z + 0.5 * shelf_height_m}"
                    rpy="0 0 0"/>
        </joint>

        <joint name="left_shelf_support_mount" type="fixed">
            <parent link="base_link_front_bumper_part"/>
            <child link="left_shelf_support"/>
            <origin xyz="${-shelf_dist_from_bumper_m - 0.5 * shelf_length_m}
                         ${0.5 * rail_width + 0.5 * shelf_width_m}
                         ${bumper_to_rail_bottom_offset_z + 0.5 * shelf_height_m}"
                    rpy="0 0 0"/>
        </joint>

        <joint name="top_shelf_mount" type="fixed">
            <parent link="base_link_front_bumper_part"/>
            <child link="top_shelf"/>
            <origin xyz="${-shelf_dist_from_bumper_m - 0.5 * shelf_length_m}
                         0.0
                         ${bumper_to_rail_bottom_offset_z + shelf_height_m - 0.5 * shelf_width_m}"
                    rpy="0 0 0"/>
        </joint>

        <joint name="arm_mount_panel_mount" type="fixed">
            <parent link="top_shelf"/>
            <child link="arm_mount_panel"/>
            <origin xyz="0
                         ${-0.5 * (rail_width) - shelf_width_m + arm_mount_panel_edge_offset_m}
                         ${0.5 * shelf_width_m + 0.5 * arm_mount_panel_height_m}"
                    rpy="0 0 0"/>
        </joint>

        <joint name="arm_mount_panel_corrected_mount" type="fixed">
            <parent link="arm_mount_panel"/>
            <child link="arm_mount_panel_dummy"/>
            <!-- <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/> -->
            <origin xyz="0 0 0" rpy="${pi / 2} ${-pi / 2} 0"/>
        </joint>
    </xacro:macro>
</robot>
