<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="fister_roboto">
    <include filename="$(find hdt)/config/urdf/common.xacro"/>
    <include filename="$(find hdt)/config/urdf/talon.xacro"/>
    <include filename="$(find hdt)/config/urdf/hdt.xacro"/>
    <include filename="$(find hdt)/config/urdf/fake_gripper.xacro"/>

    <xacro:talon />
    <xacro:hdt_arm mounting_link="base_link" mounting_origin="${base_length/2-0.1} 0.0 ${wheel_radius}"/>
    <xacro:fake_gripper mounting_link="arm_7_gripper_lift_link" mounting_origin="${length7+0.075} 0.0 0.0"/>
</robot>

