<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="andalite">
    <include filename="$(find andalite_description)/urdf/common.xacro"/>
    <include filename="$(find husky_description)/urdf/base.urdf.xacro"/>
    <include filename="$(find andalite_description)/urdf/hdt.xacro"/>
    <include filename="$(find andalite_description)/urdf/fake_gripper.xacro"/>
    <include filename="$(find andalite_description)/urdf/shelf.xacro"/>
    <include filename="$(find andalite_description)/urdf/kinect_camera.urdf.xacro"/>

    <!-- describe the fixed front bumper to shelf transforms -->

    <!-- values computed from diagrams -->
    <!-- <xacro:property name="rail_width" value="0.421"/>  -->
    <!-- <xacro:property name="shelf_dist_from_bumper_m" value="0.10795"/> -->
    <!-- <xacro:property name="bumper_to_rail_bottom_offset_z" value="0.132"/> -->

    <!-- values measured from husky at lab -->
    <!-- <xacro:property name="rail_width" value="0.418"/> -->
    <!-- <xacro:property name="shelf_dist_from_bumper_m" value="0.10795"/> -->
    <!-- <xacro:property name="bumper_to_rail_bottom_offset_z" value="0.132"/> -->

    <!-- values measured on 2014-07-08 (and averaged with previous values) -->
    <xacro:property name="rail_width" value="0.419"/>
    <xacro:property name="shelf_dist_from_bumper_m" value="0.099475"/>
    <xacro:property name="bumper_to_rail_bottom_offset_z" value="0.1395"/>

    <!-- describe the fixed top_shelf to kinect_base_link transform -->

    <!-- <xacro:property name="kinect_side_edge_depth_offset_m" value="0.132"/> -->  <!-- depth lens measured from left edge of top shelf -->
    <!-- <xacro:property name="kinect_front_edge_offset_m" value=".01097"/> -->      <!-- depth lens measured from front edge of top shelf -->
    <!-- <xacro:property name="kinect_height_offset_m" value="0.01"/> -->            <!-- depth lens measured from top edge of top shelf -->
    <!-- <xacro:property name="kinect_depth_to_camera_offset_ym" value="-0.02"/> --> <!-- offset from depth lens to camera_link in y -->

    <!-- values measured on 2014-07-08 -->
    <xacro:property name="kinect_side_edge_depth_offset_m" value="0.125"/>
    <xacro:property name="kinect_front_edge_offset_m" value=".048"/>

    <!-- Build the robot -->

    <xacro:husky_shelf
        bumper_frame="base_link_front_bumper_part"
        bumper_to_shelf_x="${shelf_dist_from_bumper_m}"
        bumper_to_shelf_z="${bumper_to_rail_bottom_offset_z}"
        rail_width="${rail_width}"/>

    <property name="cal_kinect_x" value="0.0"/>
    <property name="cal_kinect_y" value="0.0"/>
    <property name="cal_kinect_z" value="0.0"/>
    <property name="cal_kinect_roll" value="0.0"/>
    <property name="cal_kinect_pitch" value="0.0"/>
    <property name="cal_kinect_yaw" value="0.0"/>

    <xacro:kinect_camera_v0 name="kinect" parent="top_shelf">
        <origin xyz="${0.5 * top_shelf_length_m - kinect_front_edge_offset_m}
                         ${0.5 * rail_width + shelf_width_m - kinect_side_edge_depth_offset_m}
                         ${0.5 * shelf_width_m}"/>
    </xacro:kinect_camera_v0>

    <xacro:hdt_arm mounting_link="arm_mount_panel_dummy" mounting_origin="0 0 0"/>

    <xacro:fake_gripper mounting_link="arm_7_gripper_lift_link" mounting_origin="0.062 0.0 0.0"/>
</robot>
